name: synbiodio_physics
description: The physics of Synbiodio
version: 0.0.1
homepage: https://github.com/synbiodio-com/sysbiodio_physics

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  meta: ^1.9.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
